version: 0.2

phases:
  build:
    commands:
      - echo Entered the build phase...
      - ./gradlew bootJar
  post_build:
    commands:
      - echo Build completed successfully
artifacts:
  files:
    - build/libs/task3.1-0.0.1-SNAPSHOT.jar
  discard-paths: yes