version: "3"

services:
  app:
    container_name: t3p1
    build: .
    env_file:
      - .env
    ports:
      - 8080:8080
  liquibase:
    image: liquibase/liquibase
    command: --defaults-file=/liquibase/changelog/liquibase.properties update

