
create table test.company_share
(
    symbol                     varchar(255)   not null
        primary key,
    avg_total_volume           bigint         null,
    calculation_price          varchar(255)   null,
    changee                    decimal(19, 2) null,
    change_percent             decimal(19, 2) null,
    close                      bigint         null,
    close_source               varchar(255)   null,
    close_time                 datetime(6)    null,
    company_name               varchar(255)   null,
    currency                   varchar(255)   null,
    delayed_price              decimal(19, 2) null,
    delayed_price_time         datetime(6)    null,
    extended_change            decimal(19, 2) null,
    extended_change_percent    decimal(19, 2) null,
    extended_price             decimal(19, 2) null,
    high_source                varchar(255)   null,
    high_time                  datetime(6)    null,
    iex_ask_price              decimal(19, 2) null,
    iex_ask_size               bigint         null,
    iex_bid_price              decimal(19, 2) null,
    iex_bid_size               bigint         null,
    iex_close                  decimal(19, 2) null,
    iex_close_time             datetime(6)    null,
    iex_last_updated           datetime(6)    null,
    iex_market_percent         decimal(19, 2) null,
    iex_open                   decimal(19, 2) null,
    iex_open_time              datetime(6)    null,
    iex_realtime_price         decimal(19, 2) null,
    iex_realtime_size          bigint         null,
    iex_volume                 bigint         null,
    isusmarket_open            bit            null,
    last_trade_time            datetime(6)    null,
    latest_price               decimal(19, 2) null,
    latest_source              varchar(255)   null,
    latest_time                varchar(255)   null,
    latest_update              datetime(6)    null,
    latest_volume              bigint         null,
    low                        bigint         null,
    low_source                 varchar(255)   null,
    low_time                   datetime(6)    null,
    market_cap                 bigint         null,
    odd_lot_delayed_price      decimal(19, 2) null,
    odd_lot_delayed_price_time datetime(6)    null,
    open                       bigint         null,
    open_source                varchar(255)   null,
    open_time                  datetime(6)    null,
    pe_ratio                   decimal(19, 2) null,
    previous_close             decimal(19, 2) null,
    previous_volume            bigint         null,
    primary_exchange           varchar(255)   null,
    volume                     bigint         null,
    week52high                 decimal(19, 2) null,
    week52low                  decimal(19, 2) null,
    ytd_change                 decimal(19, 2) null
);

insert into test.company_share (symbol, company_name, currency)
values ('first', '1 company', 'USD'),
       ('second', '2 company', 'EUR'),
       ('third', '3 company', 'RUR'),
       ('fourth', '4 company', 'USD'),
       ('fifth', '5 company', 'EUR'),
       ('sixth', '6 company', 'RUR'),
       ('seventh', '7 company', 'USD'),
       ('eighth', '8 company', 'EUR'),
       ('ninth', '9 company', 'RUR');