server:
  port: 5000

spring:
  jpa:
    hibernate:
      ddl-auto: none
      show-sql: false
      properties:
        hibernate:
          format-sql: false
  main:
    banner-mode: off
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  liquibase:
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    driver-class-name: ${spring.datasource.driver-class-name}
    change-log: db/changelog.xml

api:
  token: ${API_TOKEN}
  trading-company: ${API_TRADING_COMPANY}
  company-share: ${API_COMPANY_SHARE}
  path-variable:
    display-percent: ${API_PATH_VARIABLE_DISPLAY_PERCENT}

cron:
  show-info: ${CRON_SHOW_INFO}
  loading-info: ${CRON_LOADING_INFO}