spring:
  jpa:
    hibernate:
      ddl-auto: none
      show-sql: false
      properties:
        hibernate:
          format-sql: false
  main:
    banner-mode: off
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${spring.datasource.url}
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}

api:
  token: ${api.token}
  trading-company: ${api.trading-company}
  company-share: ${api.company-share}
  path-variable:
    display-percent: ${api.path-variable.display-percent}

cron:
  show-info: ${cron.show-info}
  loading-info: ${cron.loading-info}